# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8000
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

#设置提供的服务名
spring:
  #配置数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:
    username:
    password:
  # 配置redis
  redis:
    # 数据库名称
    database: 0
    host: 127.0.0.1
    jedis:
      pool:
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 8
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 8
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: 1000ms
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms
    password: 'mni722'
    port: 6379

mybatis-plus:
  #  dao-locations: classpath:mybatis/**/*Mapper.xml
  mapper-locations: classpath*:mybatis/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.blog2.backend
