# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8000
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 设置提供的服务名
spring:
  #配置数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.107.80.19:3306/blog2?useUnicode=true&characterEncoding=utf8
    username: 722
    password: mni722
  # 配置redis
  redis:
    host: 127.0.0.1
    #    password: "mni722"
    # 数据库索引 默认0
    database: 0
    port: 6379
    # 超时时间 Duration类型 3秒
    timeout: 3S

# logback
logging:
  pattern:
    file: "goodtimp.log.%d{yyyy-MM-dd HH:mm:ss}.log"
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
  path: "./logs"
  file:
    max-history: 30
    max-size: 10MB
#  level:
#    root: INFO

mybatis-plus:
  #  dao-locations: classpath:mybatis/**/*Mapper.xml
  mapper-locations: classpath*:mybatis/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.blog2.backend
